# Git Aliases
alias gs="git status"
alias ga="git add"
alias gl="git log"
alias gc="git commit"
alias gpull="git pull"
alias gpush="git push"
alias gre="git reset"
alias gch="git checkout"
alias gd="git difftool"
alias gb="git branch"
alias gt="git tag"
alias g="git"
